other: #51 add tip for isEnd function loop
Ubugeeei/chibivue pull request #231
Opened 2024-01-07 16:10 UTC by shoma-mano

resolve #51
I couldn't find clear reason for loop, so this tip is just [things ubugeei said in discord](https://discord.com/channels/1190269119426215976/1190269627012493313/1191814911068754010) mostly.

2024-01-07 16:25 UTC, Ubugeeei requested changes
@shoma-mano 

Great explain!

Could you update `book/src/en` to be the same? 😄

2024-01-07 16:25 UTC, Ubugeeei commented on book/online-book/src/10-minimum-example/070-more-complex-parser.md
> +```
Please remove semi-colons and double quotes.

2024-01-08 02:44 UTC, shoma-mano commented on book/online-book/src/10-minimum-example/070-more-complex-parser.md
> +```
I'm not sure my change that removes semi-colons and double quotes is ok, but I removed them anyway.

2024-01-08 04:11 UTC, Ubugeeei commented on book/online-book/src/10-minimum-example/070-more-complex-parser.md
> +```
Yep! This is fine.
I made a comprehensive commit regarding this format issue yesterday, but it seems like it hasn't been reflected in your branch. (Please sync it.)

2024-01-08 04:12 UTC, Ubugeeei approved these changes

2024-01-08 04:12 UTC, merged