fix: 📌Fixed type error "Cannot find module 'rollup/parseAst'" in Minimum Example sample code.
Ubugeeei/chibivue pull request #242
Opened 2024-01-11 00:38 UTC by madogiwa0124

related: https://github.com/Ubugeeei/chibivue/issues/237

As shown below, a type error TS2307 occurs in `vite@5.0.10`.

```sh
$ cd book/impls/10_minimum_example/070_sfc_compiler2
$ pnpm install
$ pnpm tsc --noEmit

../../../../node_modules/.pnpm/vite@5.0.10_@types+node@20.10.5/node_modules/vite/dist/node/index.d.ts:6:41 - error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.

6 export { parseAst, parseAstAsync } from 'rollup/parseAst';
                                          ~~~~~~~~~~~~~~~~~

Found 1 error in ../../../../node_modules/.pnpm/vite@5.0.10_@types+node@20.10.5/node_modules/vite/dist/node/index.d.ts:6
```

Therefore, changed `moduleResolution` to `bundler` in Minimum Example sample code.

2024-01-11 14:08 UTC, Ubugeeei commented
@madogiwa0124 
Thanks!
Hmm, this seems like a bit of a challenging issue. 
As consider some audience, perhaps it would be best to consider rewriting everything from the setup chapter. 😓
Would you mind revising the entire PR? 
If reviewing their contributions becomes bothersome for you, I'd be happy to assist.

2024-01-11 14:10 UTC, Ubugeeei requested changes
https://github.com/Ubugeeei/chibivue/pull/242#issuecomment-1887238016

2024-01-12 21:59 UTC, madogiwa0124 commented
@Ubugeeei 

Thanks for the review!

I see, so the `tsconfig.json` in the docs and the `tsconfig.json` in the sample implementation should be changed from `moduleResolution` to `Bundler` regardless of the type error? 👀. 

If there is no conflict, I would like to change the `moduleResolution` in the "Getting Started" and "Minimam Example" sample code in this PR and in the tsconfig.json in the documentation to `Bundler` first? What do you think ?

If you want to modify all the sample code and documentation at once, that's fine 😄.

2024-01-13 05:32 UTC, Ubugeeei commented
@madogiwa0124 

> If there is no conflict, I would like to change the moduleResolution in the "Getting Started" and "Minimam Example" sample code in this PR and in the tsconfig.json in the documentation to Bundler first? What do you think ?

I think it's necessary to make changes to the code that is crucial to the context of the chapters all at once, as partially updating it might confuse the readers due to the significance of the context.
.
.
.
.
.
However, since it's already broken, I'm starting to think maybe we shouldn't worry about that too much and should just go ahead and merge it first. 🫠.
.
.
Shall we go with that?

2024-01-13 07:05 UTC, madogiwa0124 commented
@Ubugeeei 

Thanks for the comment !

> I think it's necessary to make changes to the code that is crucial to the context of the chapters all at once, as partially updating it might confuse the readers due to the significance of the context.

I get what you're saying. Here are the commits I tried to correct the `moduleResolution` in all the `tsconfig.json` to `bundler` that are causing the type errors in the docs and in the sample code .

* https://github.com/madogiwa0124/chibivue/commit/3aa1d28a5092cc10e22c987717ac9470af5edb2b

I confirmed that "Cannot find module 'rollup/parseAst'" does not occur locally.

The difference is a bit large, but what do you think ? 👀 

If it looks OK, I will update the Pull Request with the contents of this commit 😄.

As an addendum, regarding the above commit, The `tsconfig.json` for each playground is now excluded.

Because it is created in vite v4.2 series and in that case, `moduleResolution` in `tsconfig.json` is `Node`.
(We may want to update this one eventually... 💦 )

```sh
nlx create-vite@4.2
Packages: +1
+
Progress: resolved 1, reused 0, downloaded 1, added 1, done
✔ Project name: … sample-vite
✔ Select a framework: › Vanilla
✔ Select a variant: › TypeScript

Scaffolding project in sample-vite...

Done. Now run:

  cd sample-vite
  pnpm install
  pnpm run dev

$ cat sample-vite/tsconfig.json 
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ESNext", "DOM"],
    "moduleResolution": "Node",
    "strict": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "skipLibCheck": true
  },
  "include": ["src"]
}
```

2024-01-14 09:54 UTC, Ubugeeei commented
@madogiwa0124 

> Because it is created in vite v4.2 series and in that case, moduleResolution in tsconfig.json is Node.
(We may want to update this one eventually... 💦 )

Yes, your are right.

> The difference is a bit large, but what do you think ? 👀

Oh! You were already working on it (?)
In that case, let's go ahead and apply all of it!
The differences are big, but it's better than being misaligned. Besides, it's already broken anyway...

2024-01-16 11:58 UTC, madogiwa0124 commented
@Ubugeeei 

> In that case, let's go ahead and apply all of it!

I tried to correct the moduleResolution in all the `tsconfig.json` to `bundler` that are causing the type errors in the docs and in the sample code 👍🏻 .

2024-01-16 13:52 UTC, Ubugeeei approved these changes
@madogiwa0124 

I truly appreciate it from the bottom of my heart. Thank you. I'll merge now!

2024-01-16 13:52 UTC, merged